# Generated by Django 5.1.4 on 2024-12-28 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='razorpay_signature',
        ),
    ]
